t1 = (10, 20, 30, "가나다", "abc", "A", True, 10, 20, 10)
print(t1)
print("---in과 not in 연산자---")
print('30' in t1)
print(30 not in t1)
print(True in t1)
print(False not in t1)
print("---시퀀스연산---")
t2 = ("파","이","썬")
print(t1+t2)
print(t1)
print(t2)
print(t2 * 3)
print("---인텍싱과 슬라이싱---")
print(t2[0]); print(t2[1]); print(t2[2]); print(t2[-1])
print(t1[:])
print(t1[::1])
print(t1[::2])
print(t1[::-1])
print(t1[0:4:1])
print("---함수들---")
print(len(t1))
#print(max(t1)); print(min(t1))
print(max((10,20, 30))); print(min((10, 20,30)))
print(max(('a', 'b', 'c'))); print(min(('a', 'b', 'c')))
print(max((True, False))); print(min((True, False)))
print(t1.count(10))
print(t1.count(20))
print("---for와 함께 사용하는 시퀀스---")
for data in t2 :
    print("#", data, "#")
print("---튜플은 변경불가---")
t2[0] = "가"
print(t2)
